name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Debug branch name
        run: |
          echo "Deleting branch: ${{ github.head_ref }}"

      - name: Delete branch
        run: |
          git push origin --delete ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Verify deletion (optional)
        run: |
          git fetch origin
          git branch -r | grep "${{ github.head_ref }}" || echo "Branch deleted successfully"