name: Delete Merged Branch

on:
  pull_request:
    types: [closed]

jobs:
  delete-branch:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Delete branch
        run: |
          git push origin --delete ${{ github.head_ref }}
        env:
          GIT_AUTHOR_NAME: "GitHub Actions"
          GIT_AUTHOR_EMAIL: "actions@github.com"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        shell: bash
        continue-on-error: true # Tiếp tục chạy ngay cả khi có lỗi (ví dụ: branch đã bị xóa trước đó)